In [1]:
# для нормализации, стандартизации
from sklearn import preprocessing

# Для графиков
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import pandas as pd

# Данные для двух столбцов
column1 = [1, 2, 3, 4, 5]
column2 = [30, 40, 35, 57, 15]

# Создание DataFrame
df = pd.DataFrame({
    'Column1': column1,
    'Column2': column2
})

In [3]:
# инициализируем нормализатор RobustScaler
r_scaler = preprocessing.RobustScaler()

# кодируем исходный датасет
df['column3'] = r_scaler.fit_transform(df[['Column2']])

round(df['column3'][2], 1)

0.0

In [4]:
df

   Column1  Column2  column3
0        1       30     -0.5
1        2       40      0.5
2        3       35      0.0
3        4       57      2.2
4        5       15     -2.0

In [7]:
df = pd.read_csv('data/new-site.csv', sep='\t')

In [8]:
df

     site  dwell-time
0       0           2
1       1          48
2       0          15
3       1          16
4       0          38
..    ...         ...
295     0          22
296     0           7
297     1         144
298     0          89
299     0         138

[300 rows x 2 columns]

In [9]:
sum_dwell_time = df.groupby('site')['dwell-time'].sum()

In [10]:
print("\nСуммарное значение dwell-time для каждого site:")
print(sum_dwell_time)

Суммарное значение dwell-time для каждого site:
site
0    16898
1    10032
Name: dwell-time, dtype: int64

In [12]:
mean_dwell_time = df.groupby('site')['dwell-time'].mean()
print("Среднее значение dwell-time для каждого site:")
print(round(mean_dwell_time, 0))

Среднее значение dwell-time для каждого site:
site
0    91.0
1    88.0
Name: dwell-time, dtype: float64

In [15]:
dwell_time_groups = df.groupby('site')['dwell-time'].apply(list).to_dict()

# Получение списков значений dwell-time для каждого site
dwell_time_site_0 = dwell_time_groups.get(0, [])
dwell_time_site_1 = dwell_time_groups.get(1, [])

print("dwell-time для site 0:", dwell_time_site_0)
print("dwell-time для site 1:", dwell_time_site_1)

dwell-time для site 0: [2, 15, 38, 571, 233, 146, 57, 54, 75, 138, 6, 30, 369, 76, 25, 233, 32, 7, 97, 79, 86, 23, 13, 34, 112, 298, 11, 80, 29, 5, 19, 192, 18, 110, 40, 404, 30, 43, 129, 7, 227, 138, 185, 16, 145, 9, 48, 158, 79, 35, 73, 149, 92, 19, 57, 67, 6, 34, 18, 6, 68, 50, 136, 10, 28, 213, 57, 170, 115, 536, 91, 222, 15, 31, 22, 24, 8, 57, 63, 107, 540, 34, 51, 6, 489, 147, 29, 49, 134, 12, 41, 196, 30, 27, 50, 74, 75, 66, 13, 38, 74, 132, 37, 41, 66, 3, 3, 35, 8, 22, 36, 241, 40, 75, 70, 140, 140, 18, 67, 52, 62, 44, 4, 82, 61, 12, 55, 116, 4, 127, 147, 19, 268, 23, 117, 70, 53, 137, 113, 172, 174, 133, 45, 117, 103, 16, 5, 105, 66, 277, 156, 285, 64, 70, 30, 95, 68, 8, 5, 27, 60, 46, 61, 11, 149, 17, 51, 33, 72, 148, 153, 43, 155, 5, 470, 28, 388, 197, 3, 25, 2, 39, 22, 7, 89, 138]
dwell-time для site 1: [48, 16, 169, 38, 336, 55, 2, 32, 21, 162, 23, 190, 107, 30, 145, 21, 78, 244, 68, 85, 72, 6, 44, 53, 140, 24, 22, 13, 80, 2, 289, 34, 28, 5, 1, 92, 67, 25, 232, 43, 131, 128, 131, 123, 66, 47, 112, 37, 48, 14, 46, 72, 69, 16, 140, 114, 63, 28, 46, 11, 41, 55, 259, 50, 113, 154, 91, 83, 121, 725, 109, 47, 6, 120, 300, 3, 23, 53, 155, 46, 21, 49, 1, 107, 85, 17, 3, 29, 26, 12, 3, 200, 135, 12, 8, 60, 22, 7, 19, 122, 83, 148, 186, 110, 107, 106, 366, 238, 100, 187, 11, 70, 100, 144]

In [13]:
import scipy.stats as stats

In [16]:
alpha = 0.05

_, p = stats.shapiro(dwell_time_site_0) # группа А

print('p-value = %.3f' % (p))

if p <= alpha:
    print('Распределение не нормальное')
else:
    print('Распределение нормальное')

p-value = 0.000
Распределение не нормальное

In [17]:
alpha = 0.05

_, p = stats.shapiro(dwell_time_site_1) # группа B

print('p-value = %.3f' % (p))

if p <= alpha:
    print('Распределение не нормальное')
else:
    print('Распределение нормальное')

p-value = 0.000
Распределение не нормальное

In [18]:
# задаём уровень значимости
alpha = 0.05 


# проводим тест
_, p = stats.mannwhitneyu(dwell_time_site_0, dwell_time_site_1)

print('p-value = {:.3f}'.format(p))

# интерпретируем результат
if p <= alpha:
    print('p-значение меньше, чем заданный уровень значимости {:.2f}. Отвергаем нулевую гипотезу.'.format(alpha))
else:
    print('p-значение больше, чем заданный уровень значимости {:.2f}. У нас нет оснований отвергнуть нулевую гипотезу.'.format(alpha))

p-value = 0.896
p-значение больше, чем заданный уровень значимости 0.05. У нас нет оснований отвергнуть нулевую гипотезу.