In [2]:
import pandas as pd
import numpy as np
solar_data = pd.read_csv('data/solarpower.csv')
solar_data.head()

         date  cum_power
0  2017-01-01    20111.0
1  2017-01-02    20112.0
2  2017-01-03    20115.0
3  2017-01-04    20117.0
4  2017-01-05    20119.0

In [6]:
print(solar_data['cum_power'])

0      20111.0
1      20112.0
2      20115.0
3      20117.0
4      20119.0
        ...
659    28101.0
660    28109.0
661    28115.0
662    28117.0
663    28120.0
Name: cum_power, Length: 664, dtype: float64

In [26]:
solar_data.loc[solar_data['cum_power'] == -1]

Empty DataFrame
Columns: [date, cum_power]
Index: []

In [25]:
solar_data.loc[647] = 27998

In [24]:
solar_data.loc[648]

date         2018-10-11
cum_power       28010.0
Name: 648, dtype: object

In [32]:
solar_data['day_power'] = pd.to_datetime(solar_data['date'])
solar_data['day_power'].dt.to_period('M')

0      2017-01
1      2017-01
2      2017-01
3      2017-01
4      2017-01
        ...
659    2018-10
660    2018-10
661    2018-10
662    2018-10
663    2018-10
Name: day_power, Length: 664, dtype: period[M]

In [34]:
mask = solar_data['day_power'] == '2017-03'
solar_data[mask]

         date  cum_power  day_power
59 2017-03-01    20318.0 2017-03-01